export const tags = {
    form : document.querySelector('form'),
    dropArea : document.getElementById('dropArea'),
    imageInput : document.getElementById('avatar'),
    fullName: document.getElementById('userName'),
    userEmail: document.getElementById('userEmail'),
    userGitHub: document.getElementById('githubUser'),
    submitBtn : document.querySelector('button'),
    userFullName: document.getElementById('user-full-name'),
    newUserName: document.querySelectorAll('span')[5],
    userEmailAddress :document.getElementById('user-email-address'),
    gitHubUserNickName : document.getElementById('user-github'),
    avatar : document.getElementById('avatar'),
    avatarImage : document.getElementById('avatarImage'), 
    events : ['dragleave','dragover','dragenter','drop'],
    formSection : document.getElementById('classSection'),
    ticketSection : document.getElementById('ticketSection'),
    backHomeBtn: document.getElementById('backHome'), 
}